using SchemaFirst.Generator.Ast;
using System.Text;

namespace SchemaFirst.Generator.Visitors;

/// <summary>
/// Generates two C# artefacts per entity:
///   1. A full <c>class</c> with all fields + navigation properties
///   2. An immutable <c>record</c> with only @exposed fields (DTO)
///      Navigation properties in DTOs reference the target's DTO type,
///      never the full entity — preventing data leaks across API boundaries.
/// </summary>
public class CSharpVisitor : IVisitor
{
    public string TargetName => "C#";

    public string Generate(SchemaNode schema)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> — do not edit manually </auto-generated>");
        sb.AppendLine();

        foreach (var entity in schema.Entities)
        {
            sb.AppendLine(GenerateEntity(entity));
            var dto = GenerateDto(entity);
            if (!string.IsNullOrEmpty(dto))
                sb.AppendLine(dto);
        }

        return sb.ToString();
    }

    //  Full entity class 

    private static string GenerateEntity(EntityNode entity)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"public class {entity.Name}");
        sb.AppendLine("{");

        // Scalar properties
        foreach (var attr in entity.ScalarAttributes)
        {
            var csType = TypeMap.ToCSharp(attr.Type, !attr.IsRequired);
            var propName = ToPascalCase(attr.Name);
            var init = attr.DefaultValue is not null
                ? $" = {attr.DefaultValue};"
                : attr is { IsRequired: true, Type: "Text" }
                    ? " = string.Empty;"
                    : "";
            sb.AppendLine($"    public {csType} {propName} {{ get; set; }}{init}");
        }

        // Navigation properties
        foreach (var attr in entity.RelationAttributes)
        {
            var propName = ToPascalCase(attr.Name);
            var navType = attr.Relation!.Kind switch
            {
                RelationType.ManyToOne => $"{attr.Type}?",
                RelationType.OneToMany or RelationType.ManyToMany => $"ICollection<{attr.Type}>",
                _ => attr.Type
            };
            var init = attr.Relation.Kind is RelationType.OneToMany or RelationType.ManyToMany
                ? $" = new List<{attr.Type}>();"
                : "";
            sb.AppendLine($"    public {navType} {propName} {{ get; set; }}{init}");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    //  DTO record (only @exposed fields) 

    private static string GenerateDto(EntityNode entity)
    {
        var exposed = entity.Attributes.Where(a => a.IsExposed).ToList();
        if (exposed.Count == 0) return string.Empty;

        var parameters = exposed.Select(attr =>
        {
            string csType;
            if (attr.Relation is not null)
            {
                // Navigation properties in DTOs reference the target DTO,
                // not the full entity — prevents accidental data exposure
                csType = attr.Relation.Kind switch
                {
                    RelationType.ManyToOne => $"{attr.Type}Dto?",
                    RelationType.OneToMany or RelationType.ManyToMany => $"IReadOnlyList<{attr.Type}Dto>",
                    _ => $"{attr.Type}Dto?"
                };
            }
            else
            {
                csType = TypeMap.ToCSharp(attr.Type, !attr.IsRequired);
            }

            return $"    {csType} {ToPascalCase(attr.Name)}";
        });

        var sb = new StringBuilder();
        sb.AppendLine($"public record {entity.Name}Dto(");
        sb.Append(string.Join(",\n", parameters));
        sb.AppendLine();
        sb.AppendLine(");");
        return sb.ToString();
    }

    private static string ToPascalCase(string name) =>
        char.ToUpper(name[0]) + name[1..];
}