using SchemaFirst.Generator.Ast;
using System.Text;

namespace SchemaFirst.Generator.Visitors;

/// <summary>
/// Generates two TypeScript artefacts per entity:
///   1. A full <c>interface</c> with all fields + navigation properties
///   2. A DTO <c>interface</c> with only @exposed fields.
///      Navigation properties reference the target DTO interface.
/// </summary>
public class TypeScriptVisitor : IVisitor
{
    public string TargetName => "TypeScript";

    public string Generate(SchemaNode schema)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> — do not edit manually </auto-generated>");
        sb.AppendLine();

        foreach (var entity in schema.Entities)
        {
            sb.AppendLine(GenerateInterface(entity));
            var dto = GenerateDtoInterface(entity);
            if (!string.IsNullOrEmpty(dto))
                sb.AppendLine(dto);
        }

        return sb.ToString();
    }

    //  Full interface 

    private static string GenerateInterface(EntityNode entity)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"export interface {entity.Name} {{");

        foreach (var attr in entity.ScalarAttributes)
        {
            var tsType = TypeMap.ToTypeScript(attr.Type);
            var optional = !attr.IsRequired ? "?" : "";
            sb.AppendLine($"  {attr.Name}{optional}: {tsType};");
        }

        foreach (var attr in entity.RelationAttributes)
        {
            var tsType = attr.Relation!.Kind switch
            {
                RelationType.ManyToOne => $"{attr.Type} | undefined",
                RelationType.OneToMany => $"{attr.Type}[]",
                RelationType.ManyToMany => $"{attr.Type}[]",
                _ => attr.Type
            };
            var optional = attr.Relation.Kind == RelationType.ManyToOne ? "?" : "";
            sb.AppendLine($"  {attr.Name}{optional}: {tsType};");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    //  DTO interface (only @exposed fields) 

    private static string GenerateDtoInterface(EntityNode entity)
    {
        var exposed = entity.Attributes.Where(a => a.IsExposed).ToList();
        if (exposed.Count == 0) return string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine($"export interface {entity.Name}Dto {{");

        foreach (var attr in exposed)
        {
            string tsType;
            string optional;
            if (attr.Relation is not null)
            {
                tsType = attr.Relation.Kind switch
                {
                    RelationType.ManyToOne => $"{attr.Type}Dto | undefined",
                    RelationType.OneToMany => $"{attr.Type}Dto[]",
                    RelationType.ManyToMany => $"{attr.Type}Dto[]",
                    _ => $"{attr.Type}Dto"
                };
                optional = attr.Relation.Kind == RelationType.ManyToOne ? "?" : "";
            }
            else
            {
                tsType = TypeMap.ToTypeScript(attr.Type);
                optional = !attr.IsRequired ? "?" : "";
            }

            sb.AppendLine($"  {attr.Name}{optional}: {tsType};");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }
}